//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanDoAnVatVer2Entities : DbContext
    {
        public BanDoAnVatVer2Entities()
            : base("name=BanDoAnVatVer2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietSize> ChiTietSizes { get; set; }
        public virtual DbSet<ChiTietTopping> ChiTietToppings { get; set; }
        public virtual DbSet<CTMA_Size> CTMA_Size { get; set; }
        public virtual DbSet<CTMA_Topp> CTMA_Topp { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<LoaiMonAn> LoaiMonAns { get; set; }
        public virtual DbSet<Mon> Mons { get; set; }
        public virtual DbSet<NguoiMua> NguoiMuas { get; set; }
        public virtual DbSet<PTThanhToan> PTThanhToans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
