//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ID_CTDH { get; set; }
        public int ID_Don { get; set; }
        public int ID_Mon { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> GiaThucTe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string ChiTietMonAn_JSON { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
