//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTopping
    {
        public int ID_Topping { get; set; }
        public string Loai_Topping { get; set; }
        public string Ten_Topping { get; set; }
        public Nullable<decimal> GiaTopp { get; set; }
    }
}
