//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMA_Size
    {
        public int ID_Mon { get; set; }
        public int ID_Size { get; set; }
        public Nullable<decimal> GiaTang { get; set; }
    
        public virtual ChiTietSize ChiTietSize { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
