//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int ID_DonHang { get; set; }
        public int ID_NguoiMua { get; set; }
        public Nullable<System.DateTime> NgayDatDon { get; set; }
        public int PTThanhToan { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TienGiaoHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual NguoiMua NguoiMua { get; set; }
        public virtual PTThanhToan PTThanhToan1 { get; set; }
    }
}
