//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int ID_GioHang { get; set; }
        public int ID_NgMua { get; set; }
        public int ID_Mon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Size { get; set; }
        public string Sweet { get; set; }
        public string Tea { get; set; }
        public string Ice { get; set; }
        public string topping { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual NguoiMua NguoiMua { get; set; }
    }
}
