//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAnVat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanDoAnVatVer2Entities2 : DbContext
    {
        public BanDoAnVatVer2Entities2()
            : base("name=BanDoAnVatVer2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTMA_Size> CTMA_Size { get; set; }
        public virtual DbSet<CTMA_Topp> CTMA_Topp { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChiTietSize> ChiTietSize { get; set; }
        public virtual DbSet<ChiTietTopping> ChiTietTopping { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<LoaiMonAn> LoaiMonAn { get; set; }
        public virtual DbSet<Mon> Mon { get; set; }
        public virtual DbSet<NguoiMua> NguoiMua { get; set; }
        public virtual DbSet<PTThanhToan> PTThanhToan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
